# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/IntegerSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IntegerSettingsWidget(object):
    def setupUi(self, IntegerSettingsWidget):
        IntegerSettingsWidget.setObjectName("IntegerSettingsWidget")
        IntegerSettingsWidget.resize(511, 415)
        self.mainLayout = QtWidgets.QVBoxLayout(IntegerSettingsWidget)
        self.mainLayout.setObjectName("mainLayout")
        self.infoLayout = QtWidgets.QFormLayout()
        self.infoLayout.setObjectName("infoLayout")
        self.columnNameLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.columnNameLabel.setObjectName("columnNameLabel")
        self.infoLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.columnNameLabel)
        self.columnNameValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.columnNameValueLabel.setObjectName("columnNameValueLabel")
        self.infoLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.columnNameValueLabel)
        self.typeLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.infoLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.typeValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.typeValueLabel.setObjectName("typeValueLabel")
        self.infoLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.typeValueLabel)
        self.nullValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.nullValueLabel.setObjectName("nullValueLabel")
        self.infoLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nullValueLabel)
        self.nullLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.nullLabel.setObjectName("nullLabel")
        self.infoLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nullLabel)
        self.defaultLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.defaultLabel.setObjectName("defaultLabel")
        self.infoLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.defaultLabel)
        self.extraLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.extraLabel.setObjectName("extraLabel")
        self.infoLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.extraLabel)
        self.defaultValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.defaultValueLabel.setObjectName("defaultValueLabel")
        self.infoLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.defaultValueLabel)
        self.extraValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.extraValueLabel.setObjectName("extraValueLabel")
        self.infoLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.extraValueLabel)
        self.keyLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.keyLabel.setObjectName("keyLabel")
        self.infoLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.keyLabel)
        self.keyValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.keyValueLabel.setObjectName("keyValueLabel")
        self.infoLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.keyValueLabel)
        self.tableLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.tableLabel.setObjectName("tableLabel")
        self.infoLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tableLabel)
        self.tableValueLabel = QtWidgets.QLabel(IntegerSettingsWidget)
        self.tableValueLabel.setObjectName("tableValueLabel")
        self.infoLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tableValueLabel)
        self.mainLayout.addLayout(self.infoLayout)
        self.settingsGroup = QtWidgets.QGroupBox(IntegerSettingsWidget)
        self.settingsGroup.setFlat(False)
        self.settingsGroup.setCheckable(False)
        self.settingsGroup.setObjectName("settingsGroup")
        self.settingsGroupLayout = QtWidgets.QFormLayout(self.settingsGroup)
        self.settingsGroupLayout.setObjectName("settingsGroupLayout")
        self.minValueLabel = QtWidgets.QLabel(self.settingsGroup)
        self.minValueLabel.setObjectName("minValueLabel")
        self.settingsGroupLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.minValueLabel)
        self.minValueEdit = QtWidgets.QSpinBox(self.settingsGroup)
        self.minValueEdit.setMinimum(-10000)
        self.minValueEdit.setMaximum(10000)
        self.minValueEdit.setObjectName("minValueEdit")
        self.settingsGroupLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.minValueEdit)
        self.maxValueLabel = QtWidgets.QLabel(self.settingsGroup)
        self.maxValueLabel.setObjectName("maxValueLabel")
        self.settingsGroupLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maxValueLabel)
        self.maxValueEdit = QtWidgets.QSpinBox(self.settingsGroup)
        self.maxValueEdit.setMinimum(-10000)
        self.maxValueEdit.setMaximum(10000)
        self.maxValueEdit.setObjectName("maxValueEdit")
        self.settingsGroupLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxValueEdit)
        self.seqGroup = QtWidgets.QGroupBox(self.settingsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqGroup.sizePolicy().hasHeightForWidth())
        self.seqGroup.setSizePolicy(sizePolicy)
        self.seqGroup.setCheckable(True)
        self.seqGroup.setObjectName("seqGroup")
        self.seqGroupLayout = QtWidgets.QFormLayout(self.seqGroup)
        self.seqGroupLayout.setObjectName("seqGroupLayout")
        self.stepLabel = QtWidgets.QLabel(self.seqGroup)
        self.stepLabel.setObjectName("stepLabel")
        self.seqGroupLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stepLabel)
        self.stepValue = QtWidgets.QSpinBox(self.seqGroup)
        self.stepValue.setObjectName("stepValue")
        self.seqGroupLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stepValue)
        self.settingsGroupLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.seqGroup)
        self.randomGroup = QtWidgets.QGroupBox(self.settingsGroup)
        self.randomGroup.setCheckable(True)
        self.randomGroup.setObjectName("randomGroup")
        self.randomGroupLayout = QtWidgets.QFormLayout(self.randomGroup)
        self.randomGroupLayout.setObjectName("randomGroupLayout")
        self.distributionLabel = QtWidgets.QLabel(self.randomGroup)
        self.distributionLabel.setObjectName("distributionLabel")
        self.randomGroupLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.distributionLabel)
        self.distributionCombo = QtWidgets.QComboBox(self.randomGroup)
        self.distributionCombo.setObjectName("distributionCombo")
        self.randomGroupLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.distributionCombo)
        self.settingsGroupLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.randomGroup)
        self.mainLayout.addWidget(self.settingsGroup)

        self.retranslateUi(IntegerSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(IntegerSettingsWidget)

    def retranslateUi(self, IntegerSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        IntegerSettingsWidget.setWindowTitle(_translate("IntegerSettingsWidget", "IntegerSettingsWidget"))
        self.columnNameLabel.setText(_translate("IntegerSettingsWidget", "Column:"))
        self.columnNameValueLabel.setText(_translate("IntegerSettingsWidget", "ColumnName"))
        self.typeLabel.setText(_translate("IntegerSettingsWidget", "Type:"))
        self.typeValueLabel.setText(_translate("IntegerSettingsWidget", "types"))
        self.nullValueLabel.setText(_translate("IntegerSettingsWidget", "no"))
        self.nullLabel.setText(_translate("IntegerSettingsWidget", "Nullable:"))
        self.defaultLabel.setText(_translate("IntegerSettingsWidget", "Default:"))
        self.extraLabel.setText(_translate("IntegerSettingsWidget", "Extra:"))
        self.defaultValueLabel.setText(_translate("IntegerSettingsWidget", "\'\'"))
        self.extraValueLabel.setText(_translate("IntegerSettingsWidget", "\'\'"))
        self.keyLabel.setText(_translate("IntegerSettingsWidget", "Key:"))
        self.keyValueLabel.setText(_translate("IntegerSettingsWidget", "\'\'"))
        self.tableLabel.setText(_translate("IntegerSettingsWidget", "Table:"))
        self.tableValueLabel.setText(_translate("IntegerSettingsWidget", "TableName"))
        self.settingsGroup.setTitle(_translate("IntegerSettingsWidget", "Generate settings"))
        self.minValueLabel.setText(_translate("IntegerSettingsWidget", "Min value: "))
        self.maxValueLabel.setText(_translate("IntegerSettingsWidget", "Max value:"))
        self.seqGroup.setTitle(_translate("IntegerSettingsWidget", "Sequentialy"))
        self.stepLabel.setText(_translate("IntegerSettingsWidget", "Step:"))
        self.randomGroup.setTitle(_translate("IntegerSettingsWidget", "Randomly"))
        self.distributionLabel.setText(_translate("IntegerSettingsWidget", "Distribution:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IntegerSettingsWidget = QtWidgets.QWidget()
    ui = Ui_IntegerSettingsWidget()
    ui.setupUi(IntegerSettingsWidget)
    IntegerSettingsWidget.show()
    sys.exit(app.exec_())

