# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SessionManager.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SessionManager(object):
    def setupUi(self, SessionManager):
        SessionManager.setObjectName("SessionManager")
        SessionManager.resize(662, 396)
        self.centralwidget = QtWidgets.QWidget(SessionManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainVLayout = QtWidgets.QVBoxLayout()
        self.mainVLayout.setObjectName("mainVLayout")
        self.mainContainer = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainContainer.sizePolicy().hasHeightForWidth())
        self.mainContainer.setSizePolicy(sizePolicy)
        self.mainContainer.setOrientation(QtCore.Qt.Horizontal)
        self.mainContainer.setObjectName("mainContainer")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.mainContainer)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.sessionsVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.sessionsVLayout.setContentsMargins(0, 0, 0, 0)
        self.sessionsVLayout.setObjectName("sessionsVLayout")
        self.sessionsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sessionsLabel.setObjectName("sessionsLabel")
        self.sessionsVLayout.addWidget(self.sessionsLabel)
        self.sessionsList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.sessionsList.setObjectName("sessionsList")
        self.sessionsVLayout.addWidget(self.sessionsList)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.mainContainer)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.settingsVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.settingsVLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsVLayout.setObjectName("settingsVLayout")
        self.settingsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.settingsLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsLabel.sizePolicy().hasHeightForWidth())
        self.settingsLabel.setSizePolicy(sizePolicy)
        self.settingsLabel.setObjectName("settingsLabel")
        self.settingsVLayout.addWidget(self.settingsLabel)
        self.settingsFormLayout = QtWidgets.QFormLayout()
        self.settingsFormLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.settingsFormLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.settingsFormLayout.setObjectName("settingsFormLayout")
        self.driverLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.driverLabel.setEnabled(False)
        self.driverLabel.setObjectName("driverLabel")
        self.settingsFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.driverLabel)
        self.driverCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.driverCombo.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driverCombo.sizePolicy().hasHeightForWidth())
        self.driverCombo.setSizePolicy(sizePolicy)
        self.driverCombo.setEditable(False)
        self.driverCombo.setObjectName("driverCombo")
        self.settingsFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.driverCombo)
        self.hostLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.hostLabel.setEnabled(False)
        self.hostLabel.setObjectName("hostLabel")
        self.settingsFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hostLabel)
        self.hostEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.hostEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostEdit.sizePolicy().hasHeightForWidth())
        self.hostEdit.setSizePolicy(sizePolicy)
        self.hostEdit.setObjectName("hostEdit")
        self.settingsFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hostEdit)
        self.userLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.userLabel.setEnabled(False)
        self.userLabel.setObjectName("userLabel")
        self.settingsFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.userLabel)
        self.userEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.userEdit.setEnabled(False)
        self.userEdit.setObjectName("userEdit")
        self.settingsFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userEdit)
        self.passwordLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.passwordLabel.setEnabled(False)
        self.passwordLabel.setObjectName("passwordLabel")
        self.settingsFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.passwordEdit.setEnabled(False)
        self.passwordEdit.setObjectName("passwordEdit")
        self.settingsFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordEdit)
        self.portLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.portLabel.setEnabled(False)
        self.portLabel.setObjectName("portLabel")
        self.settingsFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portSpin = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.portSpin.setEnabled(False)
        self.portSpin.setMaximum(65533)
        self.portSpin.setProperty("value", 3306)
        self.portSpin.setObjectName("portSpin")
        self.settingsFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.portSpin)
        self.settingsVLayout.addLayout(self.settingsFormLayout)
        self.mainVLayout.addWidget(self.mainContainer)
        self.buttonsHLayout = QtWidgets.QHBoxLayout()
        self.buttonsHLayout.setObjectName("buttonsHLayout")
        self.newBtn = QtWidgets.QPushButton(self.centralwidget)
        self.newBtn.setObjectName("newBtn")
        self.buttonsHLayout.addWidget(self.newBtn)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setEnabled(False)
        self.saveBtn.setObjectName("saveBtn")
        self.buttonsHLayout.addWidget(self.saveBtn)
        self.celeteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.celeteBtn.setEnabled(False)
        self.celeteBtn.setObjectName("celeteBtn")
        self.buttonsHLayout.addWidget(self.celeteBtn)
        spacerItem = QtWidgets.QSpacerItem(13, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsHLayout.addItem(spacerItem)
        self.openBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openBtn.setEnabled(False)
        self.openBtn.setObjectName("openBtn")
        self.buttonsHLayout.addWidget(self.openBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttonsHLayout.addWidget(self.cancelBtn)
        self.mainVLayout.addLayout(self.buttonsHLayout)
        self.gridLayout.addLayout(self.mainVLayout, 0, 0, 1, 1)
        SessionManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(SessionManager)
        self.cancelBtn.clicked.connect(SessionManager.close)
        QtCore.QMetaObject.connectSlotsByName(SessionManager)

    def retranslateUi(self, SessionManager):
        _translate = QtCore.QCoreApplication.translate
        SessionManager.setWindowTitle(_translate("SessionManager", "SessionManager"))
        self.sessionsLabel.setText(_translate("SessionManager", "Sessions"))
        self.settingsLabel.setText(_translate("SessionManager", "Settings"))
        self.driverLabel.setText(_translate("SessionManager", "Database driver:"))
        self.hostLabel.setText(_translate("SessionManager", "Hostname / IP:"))
        self.userLabel.setText(_translate("SessionManager", "User:"))
        self.passwordLabel.setText(_translate("SessionManager", "Password:"))
        self.portLabel.setText(_translate("SessionManager", "Port:"))
        self.newBtn.setText(_translate("SessionManager", "New"))
        self.saveBtn.setText(_translate("SessionManager", "Save"))
        self.celeteBtn.setText(_translate("SessionManager", "Delete"))
        self.openBtn.setText(_translate("SessionManager", "Open"))
        self.cancelBtn.setText(_translate("SessionManager", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SessionManager = QtWidgets.QMainWindow()
    ui = Ui_SessionManager()
    ui.setupUi(SessionManager)
    SessionManager.show()
    sys.exit(app.exec_())

