# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/StringSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StringSettingsWidget(object):
    def setupUi(self, StringSettingsWidget):
        StringSettingsWidget.setObjectName("StringSettingsWidget")
        StringSettingsWidget.resize(511, 415)
        self.mainLayout = QtWidgets.QVBoxLayout(StringSettingsWidget)
        self.mainLayout.setObjectName("mainLayout")
        self.infoLayout = QtWidgets.QFormLayout()
        self.infoLayout.setObjectName("infoLayout")
        self.columnNameLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.columnNameLabel.setObjectName("columnNameLabel")
        self.infoLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.columnNameLabel)
        self.columnNameValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.columnNameValueLabel.setObjectName("columnNameValueLabel")
        self.infoLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.columnNameValueLabel)
        self.typeLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.infoLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.typeValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.typeValueLabel.setObjectName("typeValueLabel")
        self.infoLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.typeValueLabel)
        self.nullValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.nullValueLabel.setObjectName("nullValueLabel")
        self.infoLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nullValueLabel)
        self.nullLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.nullLabel.setObjectName("nullLabel")
        self.infoLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nullLabel)
        self.defaultLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.defaultLabel.setObjectName("defaultLabel")
        self.infoLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.defaultLabel)
        self.extraLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.extraLabel.setObjectName("extraLabel")
        self.infoLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.extraLabel)
        self.defaultValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.defaultValueLabel.setObjectName("defaultValueLabel")
        self.infoLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.defaultValueLabel)
        self.extraValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.extraValueLabel.setObjectName("extraValueLabel")
        self.infoLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.extraValueLabel)
        self.keyLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.keyLabel.setObjectName("keyLabel")
        self.infoLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.keyLabel)
        self.keyValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.keyValueLabel.setObjectName("keyValueLabel")
        self.infoLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.keyValueLabel)
        self.tableLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.tableLabel.setObjectName("tableLabel")
        self.infoLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tableLabel)
        self.tableValueLabel = QtWidgets.QLabel(StringSettingsWidget)
        self.tableValueLabel.setObjectName("tableValueLabel")
        self.infoLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tableValueLabel)
        self.mainLayout.addLayout(self.infoLayout)
        self.settingsGroup = QtWidgets.QGroupBox(StringSettingsWidget)
        self.settingsGroup.setFlat(False)
        self.settingsGroup.setCheckable(False)
        self.settingsGroup.setObjectName("settingsGroup")
        self.settingsGroupLayout = QtWidgets.QFormLayout(self.settingsGroup)
        self.settingsGroupLayout.setObjectName("settingsGroupLayout")
        self.minLenLabel = QtWidgets.QLabel(self.settingsGroup)
        self.minLenLabel.setObjectName("minLenLabel")
        self.settingsGroupLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.minLenLabel)
        self.minLenSpin = QtWidgets.QSpinBox(self.settingsGroup)
        self.minLenSpin.setObjectName("minLenSpin")
        self.settingsGroupLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.minLenSpin)
        self.maxLenLabel = QtWidgets.QLabel(self.settingsGroup)
        self.maxLenLabel.setObjectName("maxLenLabel")
        self.settingsGroupLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maxLenLabel)
        self.maxLenSpin = QtWidgets.QSpinBox(self.settingsGroup)
        self.maxLenSpin.setObjectName("maxLenSpin")
        self.settingsGroupLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxLenSpin)
        self.randGroup = QtWidgets.QGroupBox(self.settingsGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.randGroup.sizePolicy().hasHeightForWidth())
        self.randGroup.setSizePolicy(sizePolicy)
        self.randGroup.setCheckable(True)
        self.randGroup.setObjectName("randGroup")
        self.seqGroupLayout = QtWidgets.QFormLayout(self.randGroup)
        self.seqGroupLayout.setObjectName("seqGroupLayout")
        self.settingsGroupLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.randGroup)
        self.dictGroup = QtWidgets.QGroupBox(self.settingsGroup)
        self.dictGroup.setCheckable(True)
        self.dictGroup.setObjectName("dictGroup")
        self.randomGroupLayout = QtWidgets.QFormLayout(self.dictGroup)
        self.randomGroupLayout.setObjectName("randomGroupLayout")
        self.dictLabel = QtWidgets.QLabel(self.dictGroup)
        self.dictLabel.setObjectName("dictLabel")
        self.randomGroupLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dictLabel)
        self.dictCombo = QtWidgets.QComboBox(self.dictGroup)
        self.dictCombo.setObjectName("dictCombo")
        self.randomGroupLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dictCombo)
        self.settingsGroupLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.dictGroup)
        self.mainLayout.addWidget(self.settingsGroup)

        self.retranslateUi(StringSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(StringSettingsWidget)

    def retranslateUi(self, StringSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        StringSettingsWidget.setWindowTitle(_translate("StringSettingsWidget", "StringSettingsWidget"))
        self.columnNameLabel.setText(_translate("StringSettingsWidget", "Column:"))
        self.columnNameValueLabel.setText(_translate("StringSettingsWidget", "ColumnName"))
        self.typeLabel.setText(_translate("StringSettingsWidget", "Type:"))
        self.typeValueLabel.setText(_translate("StringSettingsWidget", "types"))
        self.nullValueLabel.setText(_translate("StringSettingsWidget", "no"))
        self.nullLabel.setText(_translate("StringSettingsWidget", "Nullable:"))
        self.defaultLabel.setText(_translate("StringSettingsWidget", "Default:"))
        self.extraLabel.setText(_translate("StringSettingsWidget", "Extra:"))
        self.defaultValueLabel.setText(_translate("StringSettingsWidget", "\'\'"))
        self.extraValueLabel.setText(_translate("StringSettingsWidget", "\'\'"))
        self.keyLabel.setText(_translate("StringSettingsWidget", "Key:"))
        self.keyValueLabel.setText(_translate("StringSettingsWidget", "\'\'"))
        self.tableLabel.setText(_translate("StringSettingsWidget", "Table:"))
        self.tableValueLabel.setText(_translate("StringSettingsWidget", "TableName"))
        self.settingsGroup.setTitle(_translate("StringSettingsWidget", "Generate settings"))
        self.minLenLabel.setText(_translate("StringSettingsWidget", "Min length: "))
        self.maxLenLabel.setText(_translate("StringSettingsWidget", "Max lentgh:"))
        self.randGroup.setTitle(_translate("StringSettingsWidget", "Random"))
        self.dictGroup.setTitle(_translate("StringSettingsWidget", "Dictionary"))
        self.dictLabel.setText(_translate("StringSettingsWidget", "Dictionary:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StringSettingsWidget = QtWidgets.QWidget()
    ui = Ui_StringSettingsWidget()
    ui.setupUi(StringSettingsWidget)
    StringSettingsWidget.show()
    sys.exit(app.exec_())

